version: '3.7'

volumes:
  vol-wp-content:
  vol-wp-images:
  vol-wp-db:

networks:
  traefik:
    external: true
    name: 'traefik_web'
  backend:

services:

  db:
    image: mariadb:11.0
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - vol-wp-db:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/zzz_my.cnf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - backend

  eris:
    depends_on:
      - db
    networks:
      - traefik
      - backend
    container_name: eris
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    build: ./
    volumes:
      - ./wp-content:/var/www/wp-content
      - ./images:/usr/src/wordpress/images
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./rootfs:/data
