version: '3.7'

volumes:
  vol-wp-content:
  vol-wp-images:
  vol-wp-db:

networks:
  traefik:
    external: true
  backend:

services:

  traefik:
    image: traefik:2.10
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: traefik
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=me@mail.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  db:
    image: mariadb:11.0
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - vol-wp-db:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/zzz_my.cnf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    networks:
      - traefik
      - backend
    container_name: wordpress
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    env_file:
      - .env
    build: ./
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./wp-content:/var/www/wp-content
      - ./images:/usr/src/wordpress/images
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./rootfs:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wordpresscp.rule=Host(`mywp.com`)"
      - "traefik.http.routers.wordpresscp.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpresscp.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.wordpresscp-secured.rule=Host(`mywp.com`)"
      - "traefik.http.routers.wordpresscp-secured.entrypoints=web-secure"
      - "traefik.http.routers.wordpresscp-secured.tls=true"
      - "traefik.http.routers.wordpresscp-secured.tls.certresolver=myhttpchallenge"

